### ISSUE TITLE
DHL API 3.1

### ISSUE THREAD

**Issue by Flaschenzug** [christoph-schaeffer/dhl-business-shipping#1]
Hi,

are you planning to update the Script to the DHL API 3.1 ?

Thanks :-)

**Comment by christoph-schaeffer** [comment]
Hey there, yes im planning to update it. I just didn't have the time for it yet.

**Comment by Flaschenzug** [comment]
> Hey there, yes im planning to update it. I just didn't have the time for it yet.

But great to hear that. Thanks!
The updates of MK-42 should help with updating it :-).

**Comment by christoph-schaeffer** [comment]
Hey there @Flaschenzug i've just released version 3.1.2

**Comment by christoph-schaeffer** [comment]
Closing the issue, since it seems to be resolved.
