### ISSUE TITLE
Warning: count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by Flaschenzug** [christoph-schaeffer/dhl-business-shipping#2]
I have a problem and can't find a solution. Maybe you have an idea.

I set up your Script, that works fine.

But while trying to use getVersion()
```
$request = new \ChristophSchaeffer\Dhl\BusinessShipping\Request\getVersion();
$response = $client->getVersion($request);
```

I get the following error:
```
Warning: count(): Parameter must be an array or an object that implements Countable in /src/Response/AbstractResponse.php on line 79
An error occured!\n
```

**Comment by christoph-schaeffer** [comment]
Hey there,

there seems to be a bug when there's no status. Fortunally in MK-42's Pull Request there is already a fix fro that. I'll accept it soon.

**Comment by christoph-schaeffer** [comment]
The Pull Request has been merged. Could you tell me if your issue still exists?

**Comment by christoph-schaeffer** [comment]
Closing the issue, since it seems to be resolved.
