### ISSUE TITLE
DHL-Geschäftskunden-ZT-Token | DHL-Geschäftskunden-ZT-Token-Passwort | DHL Geschäftskundenportal

### ISSUE THREAD

**Issue by ixopo** [christoph-schaeffer/dhl-business-shipping#20]
Hi Christoph,

i just try to update from 3.1 to 3.2 and try figure out where to find the "DHL-Geschäftskunden-ZT-Token" and "DHL-Geschäftskunden-ZT-Token-Passwort" for the TrackingClient. In my "Geschäftskundenportal" under "Persönliche Daten" => "Verfolgen alt" is the only point where i can find some login data. However they ask me to delete my old one (The "Verfolgen **alt**" also confuses me somehow):

`Hinterlegen Sie Ihre persönlichen Zugangsinformationen (Benutzername und Passwort) für die DHL Sendungsverfolgung für Geschäftskunden (nolb.dhl.de bzw. nolbusiness.dhl.de) um die Funktionen Sendungssuche (alt) sowie ggf. Proactive Reports hier im Portal nutzen zu können. Löschen Sie hierzu zunächst Ihre bestehende Berechtigung über den Button "Löschen".`

**Löschen Sie hierzu zunächst Ihre bestehende Berechtigung über den Button "Löschen"**

Is that what i wann do to get the login credentials to use for the TrackingClient ?
Thanks for clarifying.
![Geschaetskundenportal](https://user-images.githubusercontent.com/98372797/163362393-c9682d96-d34c-4b21-b8d1-33aa50154d25.png)

**Comment by christoph-schaeffer** [comment]
Hello @ixopo 

thank you for using my library :-)

Unfortunately im not really sure either, because i don't have access to a dhl business account right now...

It would be great if you just contact the dhl business support about that and maybe post what they told you here aswell. Maybe it helps somebody else.

The Tracking Credentials are different from the shipment credentials, because they are 2 seperate dhl apis.

Those ZT Credentials usually consist of a token that starts with "zt" followed by numbers and a password, which you can set yourself

@

**Comment by wolfgangmauer** [comment]
You have to call the technical support for business customers, there you can apply for a ZT token.

**Comment by ixopo** [comment]
Thank you both for your quick replies!

I also found additional informations in "https://entwickler.dhl.de/" if you go to menuitem "Sendungsverfolgung" => "Authentifizierung" they tell you to contact DHL Business Customer Service to get productive data:

`
User:              ZT-Kennung mit DASS Freigabe

Signature:      Passwort ZT-Kennung`

I will contact them later and let you know.

**Comment by ixopo** [comment]
Yes, so you definetly have to contact DHL Business Customer Service, they will send you then the User and Pass. I got it from them after one day and the awesome library from Christoph with Tracking works fine with that logindata!

**Comment by xerc** [comment]
ref. https://nolbusiness.dhl.de/nextt-online-business/jsp/login.do ; not sure how long this will work
"Im Rahmen der Bereitstellung der verbesserten Sendungsverfolgung für Geschäftskunden werden wir dieses System in wenigen Monaten abschalten. Dazu informieren wir Sie rechtzeitig an dieser Stelle über Schritte zur Umstellung Ihres Benutzers.
Bis dahin können Sie sowohl dieses System weiterhin nutzen als auch – falls Sie bereits einen Zugang haben – die neue Funktion „Verfolgen Paket & Waren“ im [Post & DHL Geschäftskundenportal](https://geschaeftskunden.dhl.de) verwenden."

**Comment by christoph-schaeffer** [comment]
@xerc i think they are talking about the old tracking api they had, However i'm not 100% sure about that. I will ask the DHL developer support about that.

thanks for letting us know

**Comment by christoph-schaeffer** [comment]
The DHL support replied, that indeed they plan to turn this api off, however there is no date to do that yet. 

It most likely will still work for a long time.

They recommended to use the international tracking api instead now.

I will implement that api in the next months into this api aswell

More information can be found here

https://developer.dhl.com/

**Comment by xerc** [comment]
may not worth your time because thankfully its pure JSON and within a totally different department @ DHL ; Freight/DGF
`curl -H 'DHL-API-Key:#' -X GET 'https://api-eu.dhl.com/track/shipments?trackingNumber=#'` => `{"shipments":[]}`
