### ISSUE TITLE
ParcelShop is missing

### ISSUE THREAD

**Issue by Manusan42** [christoph-schaeffer/dhl-business-shipping#24]
Is there a reason the ParcelShop is missing for Shipment.Receiver?
I reviewed the national and international addressing specification which states for all non-German receivers "ParcelShop" instead of "Postfiliale". The xsd-schema also states for PostfilialeType "Type of Postfiliale (Receiver is in Germany)" and for ParcelShopType "Type of ParcelShop (Receiver is in Europe)".

**Comment by christoph-schaeffer** [comment]
Hello @Manusan42 

thank you for letting me know that that property is missing.

There is no reason why it hasnt been added. I think i actually just didnt see it.

I will add it in the next weeks. Meanwhile you can just set it dynamically. 👍

**Comment by christoph-schaeffer** [comment]
@Manusan42 in Version 3.3.2 the ParcelShop property has been added.
